name: Auto Apply PR Review Changes

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write

jobs:
  apply-changes:
    if: ${{ github.event.review.state == 'changes_requested' }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ env.GH_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js (>=20)
        uses: actions/setup-node@v3
        with:
          node-version: '>=20'

      - name: Install OpenAI Codex CLI
        run: npm install -g @openai/codex

      - name: Apply review changes using Codex
        shell: bash
        run: |
          review_body="${{ github.event.review.body }}"
          pr_num="${{ github.event.pull_request.number }}"
          prompt="Review for PR #${pr_num} requests the following changes:\n\n${review_body}\n\nPlease update the code to satisfy these change requests."
          codex --full-auto --quiet "$prompt"

      - name: Generate AI-powered commit message
        id: gen_commit_msg
        shell: bash
        run: |
          diff=$(git diff || true)
          payload=$(jq -n --arg diff "$diff" \
            '{
              model: "gpt-4o-mini",
              messages: [
                {role:"system", content:"You are an expert at writing concise, imperative git commit messages. Respond with exactly one line in the form `verb: description`."},
                {role:"user", content:"Diff:\n\($diff)\n\nWrite a one-line commit message."}
              ],
              max_tokens: 50
            }')
          commit_msg=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "$payload" \
            | jq -r '.choices[0].message.content' \
            | head -n1)
          if [[ -z "$commit_msg" ]] || [[ "$commit_msg" == "null" ]]; then
            commit_msg="chore: apply requested changes"
          fi
          echo "commit_message=$commit_msg" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          add_options: '-A'
          commit_message: ${{ steps.gen_commit_msg.outputs.commit_message }}
          branch: ${{ github.event.pull_request.head.ref }}
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
        env:
          GITHUB_TOKEN: ${{ env.GH_TOKEN }}
