name: Apply Requested PR Changes

permissions:
  contents: write

on:
  pull_request_review:
    types: [submitted]

jobs:
  apply-changes:
    if: ${{ github.event.review.state == 'changes_requested' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Node.js (>=20)
        uses: actions/setup-node@v3
        with:
          node-version: '>=20'
      - name: Install OpenAI Codex CLI
        run: npm install -g @openai/codex
      - name: Set OpenAI API Key
        run: echo "OPENAI_API_KEY=${{ secrets.open_api_key }}" >> $GITHUB_ENV
        shell: bash
      - name: Generate edits with Codex
        run: |
          review_body="${{ github.event.review.body }}"
          prompt="Apply the following requested changes to the codebase:\n\n${review_body}"
          codex --full-auto --quiet "$prompt"
        shell: bash
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes detected; creating an empty commit to apply review request"
            git commit --allow-empty -m "chore: apply requested changes for PR #${{ github.event.pull_request.number }}"
          else
            git commit -m "chore: apply requested changes for PR #${{ github.event.pull_request.number }}"
          fi
          git push
        shell: bash